//
//  UIColor+ZBAdditions.swift
//
//  Generated by Zeplin on 10/20/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var zbWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class var zbWhite60: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.6)
	}

	class var zbMkgold: UIColor {
		return UIColor(red: 171.0 / 255.0, green: 153.0 / 255.0, blue: 98.0 / 255.0, alpha: 1.0)
	}
}
