//
//  UIColor+ZTBAdditions.swift
//
//  Generated by Zeplin on 10/29/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var ztbWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class var ztbWhite60: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.6)
	}

	class var ztbMkgold: UIColor {
		return UIColor(red: 171.0 / 255.0, green: 153.0 / 255.0, blue: 98.0 / 255.0, alpha: 1.0)
	}

	class var ztbSlateGrey: UIColor {
		return UIColor(red: 82.0 / 255.0, green: 79.0 / 255.0, blue: 85.0 / 255.0, alpha: 1.0)
	}

	class var ztbCoolGrey: UIColor {
		return UIColor(red: 160.0 / 255.0, green: 159.0 / 255.0, blue: 176.0 / 255.0, alpha: 1.0)
	}
}
